add settings import/export to fontSettings
GoogleChrome/chrome-extensions-samples pull request #1037
Opened 2023-11-28 00:11 UTC by patrickkettner

The advanced font settings is the repo for [Advanced Font Settings](https://chrome.google.com/webstore/detail/advanced-font-settings/caclkomlalccbpcdllchkeecicepbmbm) repo. A developer reached out to request this functionality, so I am updating the sample for approval before publishing it.

2023-11-28 11:00 UTC, oliverdunk requested changes
Left a couple of comments but otherwise this seems reasonable, thanks for working on it :)

2023-11-28 11:00 UTC, oliverdunk commented on api-samples/fontSettings/fontSettings Advanced/options.js
> +    scriptData.forEach(async ({ fontId, genericFamily }) => {
We should probably handle bad data here, e.g `configuredFonts` where `scriptData` does not exist or is not an array?

2023-11-28 11:00 UTC, oliverdunk commented on api-samples/fontSettings/fontSettings Advanced/options.js
> +        genericFamily,
We should probably handle bad data here, e.g fontID or genericFamily does not exist or is not the right datatype?

2023-11-28 21:05 UTC, patrickkettner commented
@oliverdunk should be ready for a rereview

2023-11-30 16:02 UTC, oliverdunk approved these changes
Haven't had a chance to test unfortunately but otherwise LGTM.

2023-11-30 16:10 UTC, merged