add Gemini API sample
GoogleChrome/chrome-extensions-samples pull request #1240
Opened 2024-07-22 20:20 UTC by sebastianbenz

2024-07-23 13:12 UTC, oliverdunk requested changes
Overall another really nice sample! Left a couple of quick comments, otherwise it looks good.

2024-07-24 12:17 UTC, sebastianbenz commented on functional-samples/ai.gemini-in-the-cloud/package.json
> +{
Not a fan of committing node_modules (even if it makes things easier). Treeshaking is a good question, usually I'd do it, but in this case ommitted it as it's a really small dep. Might make sense though to always do it by default...

2024-07-24 12:19 UTC, patrickkettner commented on functional-samples/ai.gemini-in-the-cloud/package.json
> +{
+1 to just always using a bundler or build step. if there are any deps at all

2024-07-24 14:50 UTC, sebastianbenz reviewed
Addressed the comments. PTAL

2024-07-24 14:50 UTC, sebastianbenz commented on functional-samples/ai.gemini-in-the-cloud/sidepanel/index.js
> +  sliderTemperature.value = generationConfig.temperature;
Seems like temperature default is not provided for the 1.5 flash model. Changed to manually setting the default.

2024-07-24 14:50 UTC, sebastianbenz commented on functional-samples/ai.gemini-in-the-cloud/sidepanel/index.js
> +    elementResponse.appendChild(document.createElement('BR'));
Then we wouldn't get paragraphs as Gemini formats them using empty lines (use "Write a poem" prompt as an example). Instead the correct thing is to not add a BR for the final paragraph.

2024-07-24 14:50 UTC, sebastianbenz commented on functional-samples/ai.gemini-in-the-cloud/package.json
> +{
Added a bundle step

2024-07-24 14:50 UTC, sebastianbenz commented on functional-samples/ai.gemini-in-the-cloud/sidepanel/index.js
> +      // maxOutputTokens: 1000,
Removed it instead...I don't think explaining the params is the job of this sample.

2024-07-25 08:03 UTC, oliverdunk approved these changes
LGTM - thanks for taking the time to address the feedback :)

2024-07-25 08:03 UTC, oliverdunk commented on functional-samples/ai.gemini-in-the-cloud/sidepanel/index.js
> +    elementResponse.appendChild(document.createElement('BR'));
Ah, that sounds good.

2024-07-25 10:08 UTC, merged