Add on device summary sample
GoogleChrome/chrome-extensions-samples pull request #1263
Opened 2024-08-21 14:00 UTC by sebastianbenz

2024-08-28 09:42 UTC, oliverdunk requested changes
Got this running, it's really great! Nice work :)

2024-08-29 18:54 UTC, sebastianbenz reviewed
PTAL

2024-08-29 18:54 UTC, sebastianbenz commented on functional-samples/ai.gemini-on-device-summarization/manifest.json
> +  "host_permissions": ["http://*/*", "https://*/*"],
Done. You're right, I'm doing the protocol check in the sw anyway.

2024-08-29 18:54 UTC, sebastianbenz commented on functional-samples/ai.gemini-on-device-summarization/sidepanel/index.css
> +.speech-bubble {
Removed the bubble part, didn't even make that much sense anyway...

2024-08-29 18:54 UTC, sebastianbenz commented on functional-samples/ai.gemini-on-device-summarization/README.md
> +4. Load this directory in Chrome as an [unpacked extension](https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked).
done

2024-08-30 15:51 UTC, oliverdunk requested changes

2024-08-30 15:51 UTC, oliverdunk commented on functional-samples/ai.gemini-on-device-summarization/background.js
> +    files: ['dist/scripts/extract-content.js']
Does this need updating?

2024-09-13 15:29 UTC, sebastianbenz commented on functional-samples/ai.gemini-on-device-summarization/background.js
> +    files: ['dist/scripts/extract-content.js']
yes!

2024-09-13 15:37 UTC, oliverdunk approved these changes
LGTM, thanks!

2024-09-13 15:38 UTC, merged