Remove notification permission from push cookbook sample
GoogleChrome/chrome-extensions-samples pull request #1365
Opened 2024-12-02 23:05 UTC by justinlulejian

As of [M132] this requirement is no longer necessary (unless the extension chooses to show a notification).

[M132]: https://chromiumdash.appspot.com/commit/ed68ac786e9a276ef2b627b7e21cf0d20cc6d798

2024-12-02 23:05 UTC, justinlulejian commented
@oliverdunk @patrickkettner to review

2024-12-03 10:49 UTC, oliverdunk requested changes
Thanks so much for helping to keep the samples up to date! Generally this looks good, just left one comment (and the same might make sense for the comment in `background.js`) 😄

2024-12-03 10:49 UTC, oliverdunk commented on functional-samples/cookbook.push/README.md
> +1. Ensure your operating system allows your browser to show desktop notification. For [MacOS](https://support.apple.com/guide/mac-help/change-notifications-settings-mh40583/mac) this, for Google Chro
This seems confusing - thoughts on just removing the line?

2024-12-09 16:37 UTC, ZetaMaster777 approved these changes

2024-12-24 21:08 UTC, merged