Added README Files For Tutorials
GoogleChrome/chrome-extensions-samples pull request #1371
Opened 2024-12-13 14:43 UTC by TrickSumo

**Changelog:-**

Added readme files for:-
1. functional-samples/tutorial.hello-world/README.md
2. functional-samples/tutorial.getting-started/README.md
3. functional-samples/tutorial.tabs-manager/README.md

Issue:- https://github.com/GoogleChrome/chrome-extensions-samples/issues/1359

2024-12-13 14:49 UTC, TrickSumo commented
@andreban Please review

2024-12-14 05:31 UTC, Scythe7x commented
S
H

2025-01-06 09:54 UTC, oliverdunk requested changes
Thanks for the contribution! I've done a first pass.

2025-01-06 09:54 UTC, oliverdunk commented on functional-samples/tutorial.getting-started/README.md
> +The purpose of this extension is to demonstrate how to create a simple chrome extension that uses default_popup, options_page, service_worker, storage and tabs API.
```suggestion
The purpose of this extension is to demonstrate how to create a simple Chrome extension that uses the `default_popup`, `options_page` and `service_worker` manifest keys and `storage` and `tabs` APIs.
```

2025-01-06 09:54 UTC, oliverdunk commented on functional-samples/tutorial.tabs-manager/popup.js
> +    'https://developer.chrome.com/docs/extensions',
Could you explain why you made this change? My initial reaction is that we shouldn't go ahead with it.

2025-01-10 14:38 UTC, TrickSumo commented on functional-samples/tutorial.tabs-manager/popup.js
> +    'https://developer.chrome.com/docs/extensions',
Hi @oliverdunk ,

Both https://developer.chrome.com/docs/extensions/* and https://developer.chrome.com/docs/webstore/* lead to 404 Not Found page, so I thought it would be good to have some valid URLs.

![image](https://github.com/user-attachments/assets/e4663cb9-7a2a-4b3e-bd35-0535fe3d0c06)

2025-01-10 14:45 UTC, TrickSumo commented on functional-samples/tutorial.tabs-manager/popup.js
> +    'https://developer.chrome.com/docs/extensions',
Sorry, I misunderstood. You are right. Those asterisks were for the wildcard. Reverting this change.

2025-01-10 15:18 UTC, oliverdunk requested changes
I went through and did a final pass - thanks again! Happy to approve this and merge once these are addressed.

2025-01-10 15:18 UTC, oliverdunk commented on functional-samples/tutorial.tabs-manager/README.md
> +3. Open thse two URLs in seperate tabs:- 'https://developer.chrome.com/docs/extensions' and 'https://developer.chrome.com/docs/extensions/reference/api'
Check this renders correctly - if not feel free to fiddle around :)

```suggestion
3. Open these two URLs in seperate tabs:
  - 'https://developer.chrome.com/docs/extensions' 
  - 'https://developer.chrome.com/docs/extensions/reference/api'
```

2025-01-10 15:18 UTC, oliverdunk commented on functional-samples/tutorial.tabs-manager/README.md
> +4. Click the extension icon in the Chrome toolbar, then select the "Tab Manager for Chrome Dev Docs" extension. A popup will appear having title "Google Dev Docs" and button named "Group Tabs". Click
```suggestion
4. Click the extension icon in the Chrome toolbar, then select the "Tab Manager for Chrome Dev Docs" extension. A popup will appear having title "Google Dev Docs" and button named "Group Tabs". Click on the button to group the two tabs.
```

2025-01-10 15:18 UTC, oliverdunk commented on functional-samples/tutorial.hello-world/README.md
> +# Getting Started With Google Chrome Extensions (Hello World!)
```suggestion
# Getting Started With Google Chrome Extensions (Hello World)
```

2025-01-10 15:18 UTC, oliverdunk commented on functional-samples/tutorial.hello-world/README.md
> +This example demonstrates how to create a simple "Hello World" Chrome extension.
```suggestion
This example demonstrates how to create a simple "Hello World" Chrome Extension.
```

2025-01-10 15:18 UTC, oliverdunk commented on functional-samples/tutorial.getting-started/README.md
> +# Getting Started With Google Chrome extensions
```suggestion
# Getting Started With Google Chrome Extensions
```

2025-01-10 15:18 UTC, oliverdunk commented on functional-samples/tutorial.getting-started/README.md
> +This is a extension used in the [Debugging extensions][1] tutorial. It changes the html body background color of active tab.
```suggestion
This is an extension used in the [Debug extensions][1] tutorial. It changes the HTML body background color of the active tab.
```

2025-01-10 15:18 UTC, oliverdunk commented on functional-samples/tutorial.getting-started/README.md
> +The purpose of this extension is to demonstrate how to create a simple Chrome extension that uses the `default_popup`, `options_page` and `service_worker` manifest keys and `storage` and `tabs` APIs.
```suggestion
The purpose of this extension is to demonstrate how to create a simple Chrome Extension that uses the `default_popup`, `options_page` and `service_worker` manifest keys and `storage` and `tabs` APIs.
```

2025-01-10 15:18 UTC, oliverdunk commented on functional-samples/tutorial.getting-started/README.md
> +6. Afterward, click the extension icon again, and the page's background color will change when you click the button in extension popup.
```suggestion
6. Afterward, click the extension icon again, and the page's background color will change when you click the button in the extension popup.
```

2025-01-10 15:18 UTC, oliverdunk commented on functional-samples/tutorial.tabs-manager/README.md
> +Purpose of this extension is to demonstrate [chrome.tabsGroup](https://developer.chrome.com/docs/extensions/reference/api/tabGroups) API to interact with the browser's tab grouping system.
```suggestion
Purpose of this extension is to demonstrate [chrome.tabsGroups](https://developer.chrome.com/docs/extensions/reference/api/tabGroups) API to interact with the browser's tab grouping system.
```

2025-01-10 17:01 UTC, TrickSumo commented on functional-samples/tutorial.tabs-manager/README.md
> +Purpose of this extension is to demonstrate [chrome.tabsGroup](https://developer.chrome.com/docs/extensions/reference/api/tabGroups) API to interact with the browser's tab grouping system.
Fixed typo, it should be tabGroups instead of tabsGroup.

2025-01-13 10:15 UTC, oliverdunk approved these changes
This looks good! Thanks for addressing all of the feedback.

2025-01-13 10:15 UTC, merged

2025-01-17 19:12 UTC, Abirhasankas143 commented
40e9576a2916266d226d357a36005876f74b1ebb

2026-10-01 13:19 UTC, robertoandino810-star commented on functional-samples/tutorial.getting-started/README.md
> +3. Go to https://developer.chrome.com/docs/extensions/get-started/tutorial/debug or any web page.
Soy mentiroso