Favicon MV3 example
GoogleChrome/chrome-extensions-samples pull request #721
Opened 2022-06-10 17:53 UTC by solomonkinard

2022-06-30 17:32 UTC, dotproto requested changes
One suggestion and a couple questions.

2022-07-11 14:33 UTC, solomonkinard commented on api/favicon/content.html
> +<script src="content.js"></script><body></body>
Done.

2022-07-11 14:33 UTC, solomonkinard commented on api/favicon/content.js
> +  const url = `chrome-extension://${chrome.runtime.id}/_favicon/?page_url=`;
Done.

2022-07-11 14:33 UTC, solomonkinard commented
Thanks.

2022-08-10 16:38 UTC, dotproto approved these changes
Thanks, @solomonkinard!

2022-08-10 16:38 UTC, merged