Update README.md to correct grammar and improve formatting
GoogleChrome/chrome-extensions-samples pull request #802
Opened 2023-01-08 13:43 UTC by CodeMaster7000

2023-01-10 16:31 UTC, jpmedley requested changes

2023-01-10 16:31 UTC, jpmedley commented on README.md
> +Note that Chrome Apps are deprecated - learn more [on the Chromium blog](https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html).
```suggestion
Note that Chrome Apps are deprecated. Learn more [on the Chromium blog](https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html).
```

2023-01-10 16:31 UTC, jpmedley commented on README.md
> +Note that Chrome Apps are deprecated - learn more [on the Chromium blog](https://blog.chromium.org/2020/08/changes-to-chrome-app-support-timeline.html).
The existing punctuation was essentially a 'comma' splice.

2023-01-10 16:31 UTC, jpmedley commented on README.md
> +To experiment with these samples, please clone this repo and use `Load Unpacked Extension`.
Why backticks?

2023-01-12 17:36 UTC, CodeMaster7000 commented
@jpmedley I have corrected the file.

2023-01-13 16:38 UTC, jpmedley approved these changes

2023-01-13 16:39 UTC, merged

2023-01-13 16:39 UTC, jpmedley commented
Thank you for your help.