Update downloads to mv3
GoogleChrome/chrome-extensions-samples pull request #844
Opened 2023-03-08 08:30 UTC by Shubham-Rasal

2023-03-18 01:13 UTC, patrickkettner commented
@oliverdunk would you be able to review?

2023-03-28 12:17 UTC, oliverdunk requested changes
Thanks so much for taking a look at this!

I left some initial thoughts - in both cases the extensions aren't working right now so it would be great to fix that. Maybe you had some extra changes that you didn't commit?

It would also be great to run the linter (`npm run lint:fix`). Note that this will change `var` to `let` which will break the `download_links` extension when you open the popup more than once, since it will try to re-declare variables. We'll need to look at fixing that.

2023-03-28 12:17 UTC, oliverdunk commented on api-samples/downloads/download_links/send_links.js
> +console.log(links)
We weren't previously logging here, so I think we should probably remove this?

2023-03-28 12:17 UTC, oliverdunk commented on api-samples/downloads/download_links/manifest.json
> +    "activeTab",
Thanks for moving to activeTab here!

2023-03-28 12:17 UTC, oliverdunk commented on api-samples/downloads/download_manager/background.js
> +    openWhenComplete = JSON.parse(localStorage.openWhenComplete);
localStorage isn't available in MV3. We'll need to update this before we can test the extension.

2023-03-28 12:22 UTC, Shubham-Rasal commented
Thanks for the feedback. On it.

2023-03-28 16:06 UTC, jpmedley commented
Does either of you have time to add READMEs to these?

2023-03-28 20:17 UTC, Shubham-Rasal commented
Yeah I will add them, once the code is ready.

2023-05-23 17:48 UTC, Shubham-Rasal commented
Sorry, I won't be able to work on this. You can go ahead with your plan

2023-05-25 12:58 UTC, closed without merging