Added Basic contextMenus sample
GoogleChrome/chrome-extensions-samples pull request #859
Opened 2023-03-23 14:35 UTC by IanStanion-google

2023-03-23 14:40 UTC, sebastianbenz commented
Can you please run `npm run lint:fix` to unblock the build? You might have to do a few manual fixes as well in case eslint can fix everything automatically.

2023-03-27 14:34 UTC, oliverdunk requested changes
Thanks for updating this! Left some initial thoughts. Could we add a README too (see api-samples/scripting for an example)? 😁

2023-03-27 16:20 UTC, jpmedley commented
@oliverdunk, Do have time to include a README using the new template? https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/README-template.md

2023-04-25 12:30 UTC, oliverdunk commented on api-samples/contextMenus/basic/sample.js
> +    if (chrome.extension.lastError) {
Can we use `chrome.runtime.lastError`? `chrome.extension` was just an alias that has been deprecated for a while :)

```suggestion
    if (chrome.runtime.lastError) {
```

2023-04-25 12:39 UTC, oliverdunk commented on api-samples/contextMenus/basic/sample.js
> +// create callback.
Does this error check work for you? On my side it doesn't seem to.

2023-04-26 17:32 UTC, IanStanion-google commented
@jpmedley Added readme file based off your template.

2023-04-28 13:55 UTC, oliverdunk approved these changes
Left one nit on the README, otherwise this looks perfect! Thanks so much for going through a few rounds of reviews on this :)

2023-04-28 13:55 UTC, oliverdunk commented on api-samples/contextMenus/basic/README.md
> +A sample extension demonstrating use the chrome.contextMenu API.
```suggestion
A sample extension demonstrating use of the chrome.contextMenus API.
```

2023-04-28 13:58 UTC, merged