Updated history sample for mv3
GoogleChrome/chrome-extensions-samples pull request #940
Opened 2023-06-05 06:50 UTC by IanStanion-google

Addresses https://github.com/GoogleChromeLabs/Extension-Docs/issues/85

2023-06-05 17:53 UTC, jpmedley requested changes

2023-06-05 17:53 UTC, jpmedley commented on api-samples/history/showHistory/manifest.json
> +  "description": "Reads your history, and shows the top ten pages you go to by typing the URL.",
```suggestion
  "description": "Reads your history and shows the top ten pages you go to by typing the URL.",
```

2023-06-05 17:53 UTC, jpmedley commented on api-samples/history/showHistory/manifest.json
> +  "description": "Reads your history, and shows the top ten pages you go to by typing the URL.",
You generally don't use a comma if there are only two in the list.

2023-06-05 17:53 UTC, jpmedley commented on api-samples/history/showHistory/showHistory.md
> +This sample demonstrates using the `chrome.history` API to display the user's most visited pages in the extension popup.
```suggestion
This sample demonstrates using the [`chrome.history`](https://developer.chrome.com/docs/extensions/reference/history/) API to display the user's most visited pages in the extension popup.
```

2023-06-05 17:53 UTC, jpmedley commented on api-samples/history/showHistory/showHistory.md
> +This sample demonstrates using the `chrome.history` API to display the user's most visited pages in the extension popup.
We should probably be linking to the API we're demonstrating.

2023-06-05 17:53 UTC, jpmedley commented on api-samples/history/showHistory/showHistory.md
> +This extension makes use of the `chrome.history.search` API to scrape the browser's history and count occurances of each visited URL.
```suggestion
This extension calls `chrome.history.search()` to scrape the browser's history and count occurrences of each visited URL.
```

2023-06-06 16:13 UTC, AmySteam commented on api-samples/history/showHistory/typedUrls.html
> +    <script src="typedUrls.js"></script>
Can you rename the script file to use lowercase and dashes? Same with the HTML file. Thanks!

Also, can you move the script tag into the body?

[File name style guide
](https://developers.google.com/style/filenames#:~:text=Guidelines%20for%20names,-Make%20file%20and&text=Use%20hyphens%2C%20not%20underscores%2C%20to,page%20names%20such%20as%20document1.
)

2023-06-09 15:11 UTC, jpmedley requested changes

2023-06-09 17:06 UTC, merged