Updated contentSettings sample for mv3
GoogleChrome/chrome-extensions-samples pull request #941
Opened 2023-06-05 07:05 UTC by IanStanion-google

Addresses: https://github.com/GoogleChromeLabs/Extension-Docs/issues/85

2023-06-05 17:57 UTC, jpmedley requested changes

2023-06-05 17:57 UTC, jpmedley commented on api-samples/contentSettings/contentSettings.md
> +This sample demonstrates the use of `chrome.contentSettings` to display the settings of a given page in the extension's popup.
```suggestion
This sample demonstrates using `chrome.contentSettings` to display the settings of a given page in the extension's popup.
```

2023-06-05 17:57 UTC, jpmedley commented on api-samples/contentSettings/contentSettings.md
> +The extension uses both the `chrome.contentSettings` and `chrome.contentSettings` APIs to check the value of each content setting on the user's currently active tab.
Is this supposed to reference `get()` and `set()`?

A writing best practice is to use the strongest verb you can.

>The extension calls `chrome.contentSettings.get()` and `chrome.contentSettings.set()` to check...

2023-06-06 16:15 UTC, AmySteam commented on api-samples/contentSettings/manifest.json
> +  "permissions": ["contentSettings", "tabs"],
@oliverdunk can we use the activeTab permission here?

2023-06-07 14:59 UTC, jpmedley approved these changes

2023-06-07 15:16 UTC, merged