Add storage sample
GoogleChrome/chrome-extensions-samples pull request #947
Opened 2023-06-08 12:37 UTC by daidr

2023-08-16 19:52 UTC, jpmedley requested changes

2023-08-16 19:52 UTC, jpmedley commented on api-samples/storage/stylizr/README.md
> +In this sample, the `chrome.storage` API is used to store the custom style string. The style will be applied to the active page when the extension's action icon is clicked.
```suggestion
In this sample, the `chrome.storage` API stores a custom style string that will be applied to the active page when the extension's action icon is clicked.
```

2023-08-17 15:59 UTC, jpmedley approved these changes

2023-08-18 15:36 UTC, oliverdunk requested changes
Left a few comments but overall this looks good. Thanks!

2023-08-18 15:36 UTC, oliverdunk commented on api-samples/storage/stylizr/options.js
> +  setTimeout(function () {
Can we add some logic to clear the timeout if this is called twice, so we don't end up running it early?

2023-08-18 15:36 UTC, oliverdunk commented on api-samples/storage/stylizr/popup.js
> +        message.innerText = 'Injected style!';
I think this should be outside of the catch block, since that will only run if there's an error? It probably means you can remove the if(e) entirely.

2023-08-18 15:36 UTC, oliverdunk commented on api-samples/storage/stylizr/popup.js
> +    message.innerHTML =
Could we rewrite this to avoid using innerHTML? I want to encourage that wherever possible :)

2023-08-21 10:25 UTC, oliverdunk requested changes
Left a couple of final comments!

2023-08-21 10:25 UTC, oliverdunk commented on api-samples/storage/stylizr/popup.js
> +(async function () {
Can we give this function a name and then call it vs. using an IIFE?

2023-08-21 10:25 UTC, oliverdunk commented on api-samples/storage/stylizr/popup.js
> +      message.innerText = 'Not allowed to inject CSS into special page.';
Could we:

- Update the message to make it a bit less presumptuous. Maybe "Injection failed. Are you on a special page?"
- Log the error to the console as well

2023-08-21 10:34 UTC, oliverdunk approved these changes
LGTM! Thanks for the work on this one 🎉

2023-08-21 10:34 UTC, merged