Add idle sample
GoogleChrome/chrome-extensions-samples pull request #961
Opened 2023-06-12 07:11 UTC by daidr

2023-07-03 10:11 UTC, oliverdunk requested changes
Left two nits, but otherwise this looks great. Side note: this is a super cool sample! I could imagine it being useful for debugging as well.

2023-07-03 10:11 UTC, oliverdunk commented on api-samples/idle/idle_simple/README.md
> +# chrome.idle
Since we only have one sample, can we move from `idle/idle_simple` to just `idle`?

2023-07-03 10:11 UTC, oliverdunk commented on api-samples/idle/idle_simple/manifest.json
> +  "permissions": ["idle", "tabs", "storage"],
Do we need the tabs permission?

2023-07-04 11:10 UTC, oliverdunk approved these changes
LGTM! Adding @AmySteam for a writing review.

2023-07-05 19:57 UTC, AmySteam commented on api-samples/idle/service-worker.js
> +    url: chrome.runtime.getURL('history.html'),
```suggestion
    url: 'history.html',
```
`runtime.getURL()` is only needed when called in a content script. This is run from the extension sw, so it's not needed.

2023-07-05 20:02 UTC, AmySteam requested changes
Thanks @daidr! 💯 

Just a few NITs

2023-07-05 20:02 UTC, AmySteam commented on api-samples/idle/README.md
> +In this sample, the `chrome.idle` API is used to detect when the user is idle and to store the history of the user's idle state.
```suggestion
In this sample, the `chrome.idle` API detects and stores the history of the user's idle state.
```

2023-07-05 20:02 UTC, AmySteam commented on api-samples/idle/README.md
> +The idle state history will be stored in the [`chrome.storage.session`](https://developer.chrome.com/docs/extensions/reference/storage/#property-session) storage area.
```suggestion
The idle state history is stored in the [`chrome.storage.session`](https://developer.chrome.com/docs/extensions/reference/storage/#property-session) storage area.
```

2023-07-07 14:40 UTC, AmySteam approved these changes
Thanks @daidr 💯 😄

2023-07-07 14:42 UTC, merged