Add topsites/basic sample
GoogleChrome/chrome-extensions-samples pull request #967
Opened 2023-06-22 06:45 UTC by daidr

1. Fix incorrect favicon path in topsites/magic8ball
2. Add topsites/basic sample

2023-07-03 09:39 UTC, oliverdunk requested changes
Left one nit, but otherwise this looks great! Thanks.

2023-07-03 09:39 UTC, oliverdunk commented on api-samples/topSites/basic/popup.js
> +// Event listener for clicks on links in a browser action popup.
```suggestion
// Event listener for clicks on links in an action popup.
```

2023-07-04 11:10 UTC, oliverdunk approved these changes
LGTM, thanks 👍

2023-07-05 19:50 UTC, AmySteam approved these changes

2023-07-06 10:19 UTC, merged